version: '3'

services:
  db:
    container_name: pg_db
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
    volumes:
      - pg-data:/data
    ports:
      - '5432:5432'

  redis:
    container_name: redis
    image: "redis:6.0-rc1-alpine"
    volumes:
      - "redis:/usr/local/etc/redis/redis.conf"
    ports:
      - "6379:6379"

  switchboard-oracle:
    container_name: switchboard-oracle
    image: "switchboardlabs/node:dev-v2-RC_01_17_23_16_22"    
    secrets:
      - PAYER_SECRETS
    environment:
      - LIVE=1
      - CLUSTER=${CLUSTER}
      - SOLANA_CLUSTER=${CLUSTER}
      - HEARTBEAT_INTERVAL=30 # Seconds
      - ORACLE_KEY=${ORACLE_KEY}
      - RPC_URL=${RPC_URL}
      - TASK_RUNNER_SOLANA_RPC=https://api.mainnet-beta.solana.com

volumes:
  pg-data:
  redis:

secrets:
  PAYER_SECRETS:
    file: ${PAYER_SECRETS}