version: '3'

services:
  db:
    container_name: pg_db
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
    volumes:
      - pg-data:/data
    ports:
      - '5432:5432'

volumes:
  pg-data: