import { type NextPage } from "next";
import Head from "next/head";
import { LinkSteamModal } from "../components/LinkSteamModal";
import useStore from "../store";
import { Header } from "../components/Header";
import { useInventory } from "../hooks/useInventory";
import Image from "next/image";
import { Puff } from "react-loading-icons";
import { ProfileModal } from "../components/ProfileModal";
import Link from "next/link";
import { ItemCard } from "../components/ItemCard";

const Home: NextPage = () => {
  const {
    authUser,
    showSteamLinkModal,
    setShowSteamLinkModal,
    csgoInventory,
    showProfileModal,
    setShowProfileModal,
  } = useStore();
  const { isLoadingInventory } = useInventory();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#000] to-[#0b0c1d] text-white">
        <Header />

        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <div className="flex flex-col items-center gap-5 sm:flex-row">
            <h1 className="text-3xl font-extrabold tracking-tight text-white sm:text-[3rem]">
              Wrap CSGO skins
            </h1>

            <span className="italic text-gray-400">
              soon available for other games
            </span>
          </div>

          {authUser && csgoInventory && (
            <div className="md grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3 md:gap-8 lg:grid-cols-4">
              {csgoInventory.descriptions
                .filter((item) => item.tradable === 1)
                .slice(0, 12)
                .map((item) => (
                  <ItemCard key={item.classid} item={item} />
                ))}
            </div>
          )}

          {authUser && isLoadingInventory && (
            <div className="flex items-center justify-center">
              <Puff className="mt-4" />
            </div>
          )}

          {!authUser && <>sign in to wrap steam skins</>}

          {authUser && !authUser.steamId && (
            <Link
              className="mr-1 mb-1 mt-6 flex w-full max-w-xl items-center justify-center gap-6 rounded bg-gray-600 px-6 py-3 text-sm font-bold uppercase text-white shadow outline-none transition-all duration-150 ease-linear hover:bg-gray-700 hover:shadow-lg focus:outline-none active:bg-gray-700"
              href="/api/auth/login"
            >
              <Image
                src="/steam-logo.webp"
                alt="steam-logo"
                width={30}
                height={30}
              />
              Link your steam account to wrap skins into nfts
            </Link>
          )}

          {authUser &&
            authUser.steamId &&
            !csgoInventory &&
            !isLoadingInventory && <div>fail to load csgo inventory</div>}

          <LinkSteamModal
            showModal={showSteamLinkModal}
            setShowModal={setShowSteamLinkModal}
          />

          <ProfileModal
            showModal={showProfileModal}
            setShowModal={setShowProfileModal}
          />
        </div>
      </main>
    </>
  );
};

export default Home;
